### ISSUE TITLE
How to change the arrow to top of the wheel?

### ISSUE THREAD

**Issue by martingutierez** [nvmao/Spin-The-Wheel#1]
I already tried to change in draw() function

if(startDeg%360 <= 270 && startDeg%360 > 180  && endDeg % 360 >= 270 && endDeg%360 < 360 ){
// winner innerHTML
}

but the spinner show different value as it should stop on 138 degree which value duck

https://imgur.com/RgSB8RK

**Comment by martingutierez** [comment]
Here is the full script


```
    <script>
        const btnSpin = document.getElementById("btnSpin");
        const canvas = document.getElementById("canvas");
        const ctx = canvas.getContext("2d");
        const width = document.getElementById("canvas").width;
        const height = document.getElementById("canvas").height;

        const centerX = width/2;
        const centerY = height/2;
        const radius = width/2;

        // let items = document.getElementsByTagName("textarea")[0].value.split("\n");
        const items = [
            { minDegree: 1, maxDegree: 36, value: 1, name: "cat" },
            { minDegree: 37, maxDegree: 72, value: 2, name: "dog" },
            { minDegree: 73, maxDegree: 108, value: 3, name: "cow" },
            { minDegree: 109, maxDegree: 144, value: 4, name: "duck" },
            { minDegree: 145, maxDegree: 180, value: 5, name: "sheep" },
            { minDegree: 181, maxDegree: 216, value: 6, name: "goat" },
            { minDegree: 217, maxDegree: 252, value: 7, name: "bird" },
            { minDegree: 253, maxDegree: 288, value: 8, name: "neko" },
            { minDegree: 289, maxDegree: 324, value: 9, name: "chicken" },
            { minDegree: 325, maxDegree: 359, value: 10, name: "patin" },
        ];
        console.log(items);

        let currentDeg = 0
        let step = 360/items.length
        let colors = []
        let itemDegs = {}

        for(let i = 0 ; i < items.length + 1;i++){
            colors.push(randomColor())
        }

        function createWheel(){
            step = 360/items.length
            colors = []
            for(let i = 0 ; i < items.length + 1;i++){
                colors.push(randomColor())
            }
            draw();
        }
        draw();

        function draw(){
            ctx.beginPath();
            ctx.arc(centerX, centerY, radius, toRad(0), toRad(360))
            ctx.fillStyle = `rgb(${33},${33},${33})`
            ctx.lineTo(centerX, centerY);
            ctx.fill()

            let startDeg = currentDeg;
            for(let i = 0 ; i < items.length; i++, startDeg += step){
                let endDeg = startDeg + step;

                color = colors[i]
                let colorStyle = `rgb(${color.r},${color.g},${color.b})`

                ctx.beginPath();
                rad = toRad(360/step);
                ctx.arc(centerX, centerY, radius - 2, toRad(startDeg), toRad(endDeg))
                let colorStyle2 = `rgb(${color.r - 30},${color.g - 30},${color.b - 30})`
                ctx.fillStyle = colorStyle2
                ctx.lineTo(centerX, centerY);
                ctx.fill()

                ctx.beginPath();
                rad = toRad(360/step);
                ctx.arc(centerX, centerY, radius - 30, toRad(startDeg), toRad(endDeg))
                ctx.fillStyle = colorStyle
                ctx.lineTo(centerX, centerY);
                ctx.fill()

                // draw text
                ctx.save();
                ctx.translate(centerX, centerY);
                ctx.rotate(toRad((startDeg + endDeg)/2));
                ctx.textAlign = "center";
                if(color.r > 150 || color.g > 150 || color.b > 150){
                    ctx.fillStyle = "#000";
                }
                else{
                    ctx.fillStyle = "#fff";
                }
                ctx.font = 'bold 24px serif';
                ctx.fillText(items[i]["name"], 130, 10);
                ctx.restore();

                // check winner
                // if(startDeg%360 <= 270 && endDeg % 360 >= 270){
                if(startDeg%360 < 270 && endDeg%360 >= 270 ){
                    document.getElementById("winner").innerHTML = items[i]["name"]
                }

            //     if(startDeg%270 <= 270 && startDeg%270 > 180 && endDeg % 270 >= 270 && endDeg%270 < 360 ){
            // console.log("startDeg",startDeg);
            // console.log("endDeg",endDeg);
            //         document.getElementById("winner").innerHTML = items[i]["name"]
            //     }
            }
        }
        

        let speed = 0
        let maxRotation = randomRange(360* 3, 360 * 6)
        let pause = false
        function animate(){
            if(pause){
                return;
            }
            speed = easeOutSine(getPercent(currentDeg ,maxRotation ,0)) * 20;
            if(speed < 0.01){
                speed = 0;
                pause = true;
                btnSpin.disabled = false;
            }
            currentDeg += speed
            draw()
            window.requestAnimationFrame(animate);
        }
        
        function spin(){
            btnSpin.disabled = true;
            // let stopDegree = randomRange(1, 360); // Degree where you want the wheel to stop
            let stopDegree = 138;
            if(speed != 0){
                return;
            }

            maxRotation = 0;
            currentDeg = 0;
            createWheel();
            draw();

            let stopItem = items.find(item => stopDegree >= item.minDegree && stopDegree <= item.maxDegree);
            console.log(stopDegree + " " + stopItem.name);
            maxRotation = (360 * 6) - randomRange(stopItem.minDegree+1, stopItem.maxDegree-1);
            itemDegs = {};
            console.log("stopItem",stopItem.name);
            console.log("maxDegree",stopItem.maxDegree);
            console.log("minDegree",stopItem.minDegree);
            console.log("max",maxRotation);
            pause = false
            window.requestAnimationFrame(animate);
        }

    </script>
```

**Comment by martingutierez** [comment]
I think there is a wrong value here
`maxRotation = (360 * 6) - randomRange(stopItem.minDegree+1, stopItem.maxDegree-1);`

since if stopdegree was 138 the max rotation would be

`360 * 6 = 2027`

if 2027 % 360 will be 6 then it will stop at cat degree
`{ minDegree: 1, maxDegree: 36, value: 1, name: "cat" },`

I also tried to change currentDeg
`let currentDeg = 270;`
to make the arrow between 0 and 360 at the top

it always stop at cat or dog
https://imgur.com/YAjgyc2
the spin wheel should stop at duck on top arrow

**Comment by nvmao** [comment]
@martingutierez 
console.log(itemDegs), you will see min max degree of each item
![image](https://github.com/nvmao/Spin-The-Wheel/assets/39910660/dd3c19df-43af-4cb5-b1ff-4f9a6c332df7)


Arrow is at 270 degree
maxRotation  = (360 * 6) = 2160
**Before rotate:** 
{
    "cat": {
        "startDeg": 0,
        "endDeg": 40
    },
    "dog": {
        "startDeg": 40,
        "endDeg": 80
    },
    "cow": {
        "startDeg": 80,
        "endDeg": 120
    },
    "duck": {
        "startDeg": 120,
        "endDeg": 160
    },
    "sheep": {
        "startDeg": 160,
        "endDeg": 200
    },
    "goat": {
        "startDeg": 200,
        "endDeg": 240
    },
    "bird": {
        "startDeg": 240,
        "endDeg": 280
    },
    "neko": {
        "startDeg": 280,
        "endDeg": 320
    },
    "chicken": {
        "startDeg": 320,
        "endDeg": 360
    }
}


**after rotate:**
{
    "cat": {
        "startDeg": 2159.317981644413,
        "endDeg": 2199.317981644413
    },
    "dog": {
        "startDeg": 2199.317981644413,
        "endDeg": 2239.317981644413
    },
    "cow": {
        "startDeg": 2239.317981644413,
        "endDeg": 2279.317981644413
    },
    "duck": {
        "startDeg": 2279.317981644413,
        "endDeg": 2319.317981644413
    },
    "sheep": {
        "startDeg": 2319.317981644413,
        "endDeg": 2359.317981644413
    },
    "goat": {
        "startDeg": 2359.317981644413,
        "endDeg": 2399.317981644413
    },
    "bird": {
        "startDeg": 2399.317981644413,
        "endDeg": 2439.317981644413
    },
    "neko": {
        "startDeg": 2439.317981644413,
        "endDeg": 2479.317981644413
    },
    "chicken": {
        "startDeg": 2479.317981644413,
        "endDeg": 2519.317981644413
    }
}

-> convert them to 360
[
    [
        "cat",
        {
            "startDeg": 359.31798164441307,
            "endDeg": 39.31798164441307
        }
    ],
    [
        "dog",
        {
            "startDeg": 39.31798164441307,
            "endDeg": 79.31798164441307
        }
    ],
    [
        "cow",
        {
            "startDeg": 79.31798164441307,
            "endDeg": 119.31798164441307
        }
    ],
    [
        "duck",
        {
            "startDeg": 119.31798164441307,
            "endDeg": 159.31798164441307
        }
    ],
    [
        "sheep",
        {
            "startDeg": 159.31798164441307,
            "endDeg": 199.31798164441307
        }
    ],
    [
        "goat",
        {
            "startDeg": 199.31798164441307,
            "endDeg": 239.31798164441307
        }
    ],
    [
        "bird",
        {
            "startDeg": 239.31798164441307,
            "endDeg": 279.31798164441307
        }
    ],
    [
        "neko",
        {
            "startDeg": 279.31798164441307,
            "endDeg": 319.31798164441307
        }
    ],
    [
        "chicken",
        {
            "startDeg": 319.31798164441307,
            "endDeg": 359.31798164441307
        }
    ]
]

result = 'bird'

**Comment by nvmao** [comment]
`<!DOCTYPE html>
<html>
<head>

    <style>
        body{
            background-color: #333;
        }

        .header{
            padding: 40px;
            color: #fff;
            margin: 0 auto;
            margin-bottom: 40px;
        }
        .header h1,p{
            text-align: center;
        }

        .wheel{
            display: flex;
            justify-content: center;
            position: relative;
        }
        .center-circle{
            width: 100px;
            height: 100px;
            border-radius: 60px;
            background-color: #fff;
            position: absolute;
            top: 50%;
            transform: translateY(-50%);
        }
        .triangle{
            width: 0; 
            height: 0; 
            border-left: 10px solid transparent;
            border-right: 10px solid transparent;
            border-top: 20px solid red; 
            position: absolute;
            top: -220%;
            right: 50%;
            transform: translateX(50%);
        }
        textarea{
            background-color: rgba(20, 20, 20, 0.2);
            caret-color: #fff;
            resize: none;
            color: #fff;
        }
        .inputArea{
            display: flex;
            justify-content: center;
            margin-top: 40px;
        }
    </style>

</head>

<body >
    <div class="header">
        <h1>WINNER</h1>
        <p id="winner">NONE</p>
    </div>
    <div class="wheel">
        <canvas class="" id="canvas" width="500" height="500"></canvas>
        <div class="center-circle" onclick="spin()">
            <div class="triangle"></div>
        </div>
        
    </div>
    <div class="inputArea" onchange="createWheel()">
        <textarea rows="20" cols="30" >cat
dog
cow
duck
sheep
goat
bird
neko
chicken</textarea>
    </div>

    <script>
        function randomColor(){
            r = Math.floor(Math.random() * 255);
            g = Math.floor(Math.random() * 255);
            b = Math.floor(Math.random() * 255);
            return {r,g,b}
        }
        function toRad(deg){
            return deg * (Math.PI / 180.0);
        }
        function randomRange(min,max){
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }
        function easeOutSine(x) {
            return Math.sin((x * Math.PI) / 2);
        }
        // get percent between 2 number
        function getPercent(input,min,max){
            return (((input - min) * 100) / (max - min))/100
        }
    </script>

    <script>
        const canvas = document.getElementById("canvas")
        const ctx = canvas.getContext("2d")
        const width = document.getElementById("canvas").width
        const height = document.getElementById("canvas").height

        const centerX = width/2
        const centerY = height/2
        const radius = width/2

        let items = document.getElementsByTagName("textarea")[0].value.split("\n");

        let currentDeg = 0
        let step = 360/items.length
        let colors = []
        let itemDegs = {}

        for(let i = 0 ; i < items.length + 1;i++){
            colors.push(randomColor())
        }

        function createWheel(){
            items = document.getElementsByTagName("textarea")[0].value.split("\n");
            step = 360/items.length
            colors = []
            for(let i = 0 ; i < items.length + 1;i++){
                colors.push(randomColor())
            }
            draw()
        }
        draw()
        console.log(itemDegs)


        function draw(){
            ctx.beginPath();
            ctx.arc(centerX, centerY, radius, toRad(0), toRad(360))
            ctx.fillStyle = `rgb(${33},${33},${33})`
            ctx.lineTo(centerX, centerY);
            ctx.fill()

            let startDeg = currentDeg;
            for(let i = 0 ; i < items.length; i++, startDeg += step){
                let endDeg = startDeg + step

                color = colors[i]
                let colorStyle = `rgb(${color.r},${color.g},${color.b})`

                ctx.beginPath();
                rad = toRad(360/step);
                ctx.arc(centerX, centerY, radius - 2, toRad(startDeg), toRad(endDeg))
                let colorStyle2 = `rgb(${color.r - 30},${color.g - 30},${color.b - 30})`
                ctx.fillStyle = colorStyle2
                ctx.lineTo(centerX, centerY);
                ctx.fill()

                ctx.beginPath();
                rad = toRad(360/step);
                ctx.arc(centerX, centerY, radius - 30, toRad(startDeg), toRad(endDeg))
                ctx.fillStyle = colorStyle
                ctx.lineTo(centerX, centerY);
                ctx.fill()

                // draw text
                ctx.save();
                ctx.translate(centerX, centerY);
                ctx.rotate(toRad((startDeg + endDeg)/2));
                ctx.textAlign = "center";
                if(color.r > 150 || color.g > 150 || color.b > 150){
                    ctx.fillStyle = "#000";
                }
                else{
                    ctx.fillStyle = "#fff";
                }
                ctx.font = 'bold 24px serif';
                ctx.fillText(items[i], 130, 10);
                ctx.restore();

                itemDegs[items[i]] = 
                    {
                    "startDeg": startDeg,
                    "endDeg" : endDeg
                    }
                
                
                console.log(itemDegs)
                arr = Object.keys(itemDegs).map((key) => [key, {
                    "startDeg": itemDegs[key].startDeg % 360,
                    "endDeg" : itemDegs[key].endDeg % 360
                }]);
                // console.log(arr)
                // let de = arr.map((x) =>({
                //     "startDeg": x.startDeg % 360,
                //     "endDeg" : x.endDeg % 360
                // }));
                console.log(arr)
                // check winner
                if(startDeg%360 < 270 && endDeg%360 >= 270 ){
                    document.getElementById("winner").innerHTML = items[i]
                }
            }
        }
        

        let speed = 0
        let maxRotation = randomRange(360* 3, 360 * 6)
        let pause = false
        function animate(){
            if(pause){
                return
            }
            speed = easeOutSine(getPercent(currentDeg ,maxRotation ,0)) * 20
            if(speed < 0.01){
                speed = 0
                pause = true
            }
            currentDeg += speed
            draw()
            window.requestAnimationFrame(animate);
        }
        
        function spin(){
            if(speed != 0){
                return
            }

            maxRotation = 0;
            currentDeg = 0
            createWheel()
            draw();

            // itemDegs['cat'].endDeg + 10
            maxRotation = (360 * 6)
            itemDegs = {}
            console.log("max",maxRotation)
            console.log(itemDegs);
            pause = false
            window.requestAnimationFrame(animate);
        }

    </script>
</body>

</html>`

**Comment by idevlinkcom** [comment]
then how to stop to a value we want? for example 320 which will show chicken

**Comment by martingutierez** [comment]
now how to stop at value we want?
for example stop at 120 degree that will stop at duck

I'm also try to set 
`let currentDeg = 270;`

so that the arrow by default pointing at between cat and chicken

**Comment by nvmao** [comment]
@martingutierez 
maxRotation = (360 * 6) - itemDegs['duck'].endDeg + 10

**Comment by martingutierez** [comment]
Here's your updated code 
https://jsfiddle.net/mc5wxafd/

it's not stop on "duck" instead will stop at dog

**Comment by martingutierez** [comment]
Ok I find out the fix for this. What you have to do is edit the maxRotation with right formula.
thanks
